language: node_js

node_js:
  - "0.11"
  - "0.10"
  - "0.8"

before_script:
  - wget http://browscap.org/stream?q=BrowsCapJSON -O /tmp/browscap.json
  - cp /tmp/browscap.json browscap.json

script:
  - "npm test"

