language: node_js
sudo: false

node_js:
  - "8.1"
  - "8.0"
  - "7.9"
  - "7.8"
  - "7.7"
  - "7.6"
  - "7.5"
  - "7.4"
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.0"
  - "6.11"
  - "6.10"
  - "6.9"
  - "6.8"
  - "6.7"
  - "6.6"
  - "6.5"
  - "6.4"
  - "6.3"
  - "6.2"
  - "6.1"
  - "6.0"
  - 5
  - 4
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

os:
  - linux

script:
  - "npm test"
